Crossovers mutators selectors
jkatan/GeneticAlgorithms pull request #3
Opened 2020-09-06 01:31 UTC by jkatan

En esta branch estarían ya implementados los componentes de mutación, cruce y selección que nos faltaban.

2020-09-06 22:08 UTC, npaganini commented on src/GeneticComponents/Implementations/Mutators/GeneMutator.java
> +        int randomGene = (int) Math.ceil(Utils.getRandomInRange(0, individualToMutate.getEquipment().size()));
Perdón, no entiendo qué hacés acá. Supuestamente deberías mutar 1 solo gen. Estas determinando que el tamaño de la cantidad de equipment (que es siempre 5?) es el rango para sacar el gen a mutar? como si el "gen" a mutar es uno de los equipments? y el 0 viene a ser el caso en el que mutás el height?

2020-09-06 22:08 UTC, npaganini commented on src/main/FindBestCombination.java
> +        //findBestCombination();
borrado?

2020-09-06 22:08 UTC, npaganini commented on src/main/FindBestCombination.java
> +        randomEquipment.add(Utils.selectRandomEquipmentFromFile(pecherasFile));
Muy bien esta modularización 👍

2020-09-06 22:19 UTC, npaganini commented on src/GeneticComponents/Implementations/ParentSelectors/RankingSelector.java
> +    }
Esto se podría parametrizar/modularizar también? lo vi en un par de selectors

2020-09-06 22:19 UTC, jkatan commented on src/GeneticComponents/Implementations/Mutators/GeneMutator.java
> +        int randomGene = (int) Math.ceil(Utils.getRandomInRange(0, individualToMutate.getEquipment().size()));
Sisi exacto. La variable randomGene vendria a ser como el "index" del gen. Si es 0, muto el height, y sino lo uso como índice en el array de equipment. 

Entonces, cada vez que se llama a este mutator, lo que hace es tomar un gen de forma aleatoria, y mutarlo (con probabilidad Pm).

2020-09-06 22:20 UTC, jkatan commented on src/main/FindBestCombination.java
> +        //findBestCombination();
Ah, lo comenté porque estaba testeando otra cosa, pero eso no debería estar comentado en la implementación final

2020-09-06 22:22 UTC, jkatan commented on src/GeneticComponents/Implementations/ParentSelectors/RankingSelector.java
> +    }
Cierto, si, se repite un poco eso, lo puedo modularizar

2020-09-06 23:13 UTC, npaganini commented on src/GeneticComponents/Implementations/ParentSelectors/DeterministicTournamentSelector.java
> +                populationCopy.remove(randomIndex);
el `remove` te devuelve el que saca, podrías hacer esto en una sola línea

2020-09-06 23:13 UTC, npaganini commented on src/GeneticComponents/Implementations/ParentSelectors/DeterministicTournamentSelector.java
> +    }
esto no conviene mudarlo al selector manager?

2020-09-06 23:22 UTC, npaganini reviewed
Bueno, me faltan ver los crossovers. Los selectors creo que están bien más allá de los comments

2020-09-06 23:54 UTC, npaganini requested changes

2020-09-06 23:54 UTC, npaganini commented on src/GeneticComponents/Implementations/Reproductors/TwoPointCrossover.java
> +        CrossoverManager.exchangeGenesInLocusRange(parent1, child1, parent2, child2, startingLocus, finishLocus);
@jkatan en este no hay que hacer lo mismo que el 1 Point. Habría que hacer que cambie [0;S] del hijo desde el índice 0 y que cambie [0;S] del mismo hijo desde el índice N (o en realidad N-1) para atrás

2020-09-06 23:59 UTC, npaganini commented on src/GeneticComponents/Implementations/Reproductors/TwoPointCrossover.java
> +        CrossoverManager.exchangeGenesInLocusRange(parent1, child1, parent2, child2, startingLocus, finishLocus);
(la cantidad de seleccionados [0;S] puede ser distinto para el que arranca desde el principio y el que arranca desde el final)

2020-09-07 00:22 UTC, npaganini approved these changes

2020-09-07 00:47 UTC, merged